FROM mcr.microsoft.com/azure-sql-edge:latest

# Variables de entorno por defecto para SQL Server
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=StrongP@ssword123
ENV MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS

# Puerto de SQL Server
EXPOSE 1433

