services:
  sqlserver:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mp-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssword123
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mp-network
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  mp-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
