FROM mcr.microsoft.com/azure-sql-edge:latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=StrongP@ssword123
ENV MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS

# Expose SQL Server port
EXPOSE 1433
